- name: variables
  hosts: web
  connection: local
  vars:
    COURSE: "Aws and Devops"
    DURATION: "120hrs"
    TRAINER: "Shiva"
  tasks:
  - name: print the variable.
    ansible.builtin.debug:
      msg: "Course is {{COURSE}}, Duration is {{DURATION}}, Trainer name is {{TRAINER}}"  